### ISSUE TITLE
Does WildFly 9 supports Jersey 2

### ISSUE THREAD

**Issue by SinhaAmit** [javaee-samples/javaee7-samples#324]
Similar to #93 I'm using Jax-rs-2.0 with Jersey 2.22.1. I added all jersey libraries in my application and I removed <extension module="org.jboss.as.jaxrs"/>, <subsystem xmlns="urn:jboss:domain:jaxrs:1.0"/> from standalone.xml to disable RestEasy dependencies. After this my application is getting deployed successfully and I'm able to see out put for MIME type TEXT_XML on browse. However for APPLICATION_XML, I'm getting below exception in my client code. I am using normal eclipse project for Rest client using Jersey, from the stack trace I can see that it's still referring to RestEasy Client. I'm not able to find from where, please help.

Exception in thread "main" javax.ws.rs.ProcessingException: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:183)
	at com.tcs.mc.Tester.main(Tester.java:24)
Caused by: javax.ws.rs.ProcessingException: could not find writer for content-type application/xml type: com.tcs.mc.Todo
	at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:40)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:138)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:117)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:341)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:558)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:524)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:423)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:281)
	... 4 more

**Comment by arun-gupta** [comment]
WildFly supports JAX-RS 2, Jersey 2 is just an implementation of JAX-RS2. WildFly uses RESTEasy instead. This is not a supported configuration.
