### ISSUE TITLE
BatchChunkExceptionTest.testBatchChunkException test fails

### ISSUE THREAD

**Issue by sermojohn** [javaee-samples/javaee7-samples#370]
This test case fails.
`java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.javaee7.batch.chunk.exception.BatchChunkExceptionTest.testBatchChunkException(BatchChunkExceptionTest.java:122)`

Steps to reproduce:
1. Checkout master branch
2. Run tests using the command `mvn test -Pwildfly-managed-arquillian -Dwildfly.version=10.1.0.Final`

**Comment by arjantijms** [comment]
Fixed now, thanks for the report.
